fullnameOverride: alertmanager

x-affinity: &defaultAffinity
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/role
              operator: In
              values:
                - middleware

service:
  apiserver:
    controller: apiserver
    ports:
      http-8080:
        port: 8080
        targetPort: http
        protocol: HTTP
      grpc-50051:
        port: 50051
        targetPort: grpc
        protocol: TCP
      metrics:
        port: 9464
        targetPort: metrics
        protocol: HTTP
  apiserver-grpc:
    enabled: true
    controller: apiserver
    labels:
      app: alertmanager-apiserver
    annotations:
      service.cloud.tencent.com/direct-access: "true"
      service.cloud.tencent.com/prevent-loopback: "true"
      service.kubernetes.io/loadbalance-id: loadbalance-id
      service.kubernetes.io/tke-existed-lbid: loadbalance-id
    ports:
      grpc-50051:
        port: 50051
        targetPort: grpc
        protocol: HTTP
    type: LoadBalancer
  ui:
    controller: ui
    ports:
      http-80:
        port: 80
        targetPort: http
        protocol: HTTP

controllers:
  apiserver:
    replicas: 2
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: "0"
    pod:
      labels:
        app: alertmanager-apiserver
        cls: "true"
      affinity:
        <<: *defaultAffinity
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: alertmanager-apiserver
                topologyKey: kubernetes.io/hostname
    containers:
      app:
        image:
          repository: registry.cn-beijing.aliyuncs.com/qqlx/alertmanager
          tag: main-7f94fee-20260725-080653
        env:
          TZ: "Asia/Shangha"
          SERVICE_NAME:
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
          ALERTMANAGER_APISERVER_SERVER_BIND: "0.0.0.0:8080"
          ALERTMANAGER_APISERVER_CONFIG_PATH: "/app/config/config.yaml"
          OTEL_SERVICE_NAME:
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://10.10.10.10:30001"
          OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
          OTEL_METRICS_EXPORTER: "prometheus"
          OTEL_EXPORTER_PROMETHEUS_PORT: "9464"
          OTEL_EXPORTER_PROMETHEUS_HOST: "0.0.0.0"
        ports:
          - name: http
            containerPort: 8080
          - name: grpc
            containerPort: 50051
          - name: metrics
            containerPort: 9464
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi

        probes:
          liveness:
            enabled: true
            type: HTTP
            path: /api/v1/healthz
            port: http
            spec:
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 3

          readiness:
            enabled: true
            type: HTTP
            path: /api/v1/healthz
            port: http
            spec:
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
              failureThreshold: 3
  ui:
    replicas: 2
    strategy: RollingUpdate
    rollingUpdate:
      unavailable: "0"
    pod:
      labels:
        app: alertmanager-ui
        cls: "true"
      affinity:
        <<: *defaultAffinity
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: alertmanager-ui
                topologyKey: kubernetes.io/hostname
    containers:
      app:
        image:
          repository: registry.cn-beijing.aliyuncs.com/qqlx/alertmanagerui
          tag: main-3d9611c-20260829-113421
        env:
          OTEL_EXPORTER_ENDPOINT: "http://10.10.10.10:30001"
          TZ: "Asia/Shanghai"
        ports:
          - containerPort: 80
            name: http
        securityContext:
          capabilities:
            add:
              - SYS_NICE

configMaps:
  apiserver-config:
    forceRename: alertmanager-apiserver-config
    enabled: true
    data:
      config.yaml: |-
        server:
          bind: 0.0.0.0:8080
          timeZone: "Asia/Shanghai"

        log:
          encoder: json
          level: info

        grpc:
          bind: 0.0.0.0:50051
          tls:
            caFile: /app/certs/ca.crt
            certFile: /app/certs/server.crt
            keyFile: /app/certs/server.key

        cronJob:
          enable: true

        mysql:
          username: user
          password: password
          host: 10.0.3.3
          port: 3306
          database: alert_manager
          maxIdleConns: 5
          maxOpenConns: 10
          maxLifetime: 30m
          debug: true

        # redis配置
        redis:
          # single sentinel
          mode: single
          host: 10.0.4.12:6379
          password: password
          # 过期时间 3s 3m 3h
          expireTime: 300s
          keyPrefix: alertmanager
          db: 0
          poolSize: 20
          minIdleConns: 10
          connMaxLifetime: 30m

        jwt:
          issuer: alertmanager
          secret: $(openssl rand -hex 32) # 使用命令生成
          accessExpireTime: 15m
          refreshExpireTime: 168h

        oauth2:
          enable: true
          providers:
            feishu:
              clientId: clientId
              clientSecret: clientSecret
              authUrl: https://accounts.feishu.cn/open-apis/authen/v1/authorize
              tokenUrl: https://open.feishu.cn/open-apis/authen/v2/oauth/token
              userInfoUrl: https://open.feishu.cn/open-apis/authen/v1/user_info
              redirectUrl: https://you.domain.com/oauth/login

        kubernetesEvents:
          exclude:
            message: "^Container image .* already present on machine$"

        alert:
          tenantKey: cluster
          receiveToken: $(openssl rand -hex 32) # 使用命令生成
          printReceivedData: true
          repeatInterval: 4h
          evaluateTemplateID: # 自己评估后得到的告警处理方式
            IDCHeartbeatFailed: # 对应该 alertName 使用的告警模板名称
              - zhongbao
              - 飞书告警模板
        internal:
          token: $(openssl rand -hex 32) # 使用命令生成

secrets:
  grpc-tls:
    forceRename: alertmanager-apiserver-grpc-tls
    labels:
      app: alertmanager-apiserver
    stringData:
      ca.crt: |-
        -----BEGIN CERTIFICATE-----
        -----END CERTIFICATE-----
      server.crt: |-
        -----BEGIN CERTIFICATE-----
        -----END CERTIFICATE-----
      server.key: |-
        -----BEGIN PRIVATE KEY-----
        -----END PRIVATE KEY-----

persistence:
  config:
    type: configMap
    identifier: apiserver-config
    advancedMounts:
      apiserver:
        app:
          - path: /app/config/
            readOnly: true
  credentials:
    type: secret
    identifier: grpc-tls
    advancedMounts:
      apiserver:
        app:
          - path: /app/certs
            readOnly: true



rawResources:
  alertmanager:
    enabled: true
    manifest:
      apiVersion: networking.istio.io/v1
      kind: VirtualService
      metadata:
        name: alertmanager
        namespace: "{{ .Release.Namespace }}"
      spec:
        gateways:
          - istio-system/ops-https
          - istio-system/ops-http
        hosts:
          - you.domain.com
        http:
        - name: api-routes
          match:
          - uri:
              prefix: /api
          route:
          - destination:
              host: "{{ .Values.service.apiserver.name }}.{{ .Release.Namespace }}.svc.cluster.local"
              port:
                number: 8080
        - name: ui-routes
          match:
          - uri:
              prefix: /
          route:
          - destination:
              host: "{{ .Values.service.ui.name }}.{{ .Release.Namespace }}.svc.cluster.local"
              port:
                number: 80

serviceMonitor:
  apiserver:
    enabled: true
    jobLabel: app
    service:
      identifier: apiserver
    endpoints:
      - interval: 15s
        port: metrics
        relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
          - __meta_kubernetes_pod_node_name
          targetLabel: node
        scheme: http