// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/alert666/api-server/model"
)

func newIDCHeartbeat(db *gorm.DB, opts ...gen.DOOption) iDCHeartbeat {
	_iDCHeartbeat := iDCHeartbeat{}

	_iDCHeartbeat.iDCHeartbeatDo.UseDB(db, opts...)
	_iDCHeartbeat.iDCHeartbeatDo.UseModel(&model.IDCHeartbeat{})

	tableName := _iDCHeartbeat.iDCHeartbeatDo.TableName()
	_iDCHeartbeat.ALL = field.NewAsterisk(tableName)
	_iDCHeartbeat.ID = field.NewInt(tableName, "id")
	_iDCHeartbeat.CreatedAt = field.NewTime(tableName, "created_at")
	_iDCHeartbeat.UpdatedAt = field.NewTime(tableName, "updated_at")
	_iDCHeartbeat.DeletedAt = field.NewField(tableName, "deleted_at")
	_iDCHeartbeat.Cluster = field.NewString(tableName, "cluster")
	_iDCHeartbeat.Node = field.NewString(tableName, "node")
	_iDCHeartbeat.IP = field.NewString(tableName, "ip")
	_iDCHeartbeat.HeartbeatTimestamp = field.NewInt64(tableName, "heartbeat_timestamp")

	_iDCHeartbeat.fillFieldMap()

	return _iDCHeartbeat
}

type iDCHeartbeat struct {
	iDCHeartbeatDo

	ALL                field.Asterisk
	ID                 field.Int // 自增主键
	CreatedAt          field.Time
	UpdatedAt          field.Time
	DeletedAt          field.Field
	Cluster            field.String // 集群名称
	Node               field.String // 节点名称
	IP                 field.String // 节点IP地址
	HeartbeatTimestamp field.Int64  // 心跳时间戳(毫秒)

	fieldMap map[string]field.Expr
}

func (i iDCHeartbeat) Table(newTableName string) *iDCHeartbeat {
	i.iDCHeartbeatDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i iDCHeartbeat) As(alias string) *iDCHeartbeat {
	i.iDCHeartbeatDo.DO = *(i.iDCHeartbeatDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *iDCHeartbeat) updateTableName(table string) *iDCHeartbeat {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt(table, "id")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.DeletedAt = field.NewField(table, "deleted_at")
	i.Cluster = field.NewString(table, "cluster")
	i.Node = field.NewString(table, "node")
	i.IP = field.NewString(table, "ip")
	i.HeartbeatTimestamp = field.NewInt64(table, "heartbeat_timestamp")

	i.fillFieldMap()

	return i
}

func (i *iDCHeartbeat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *iDCHeartbeat) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 8)
	i.fieldMap["id"] = i.ID
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
	i.fieldMap["cluster"] = i.Cluster
	i.fieldMap["node"] = i.Node
	i.fieldMap["ip"] = i.IP
	i.fieldMap["heartbeat_timestamp"] = i.HeartbeatTimestamp
}

func (i iDCHeartbeat) clone(db *gorm.DB) iDCHeartbeat {
	i.iDCHeartbeatDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i iDCHeartbeat) replaceDB(db *gorm.DB) iDCHeartbeat {
	i.iDCHeartbeatDo.ReplaceDB(db)
	return i
}

type iDCHeartbeatDo struct{ gen.DO }

type IIDCHeartbeatDo interface {
	gen.SubQuery
	Debug() IIDCHeartbeatDo
	WithContext(ctx context.Context) IIDCHeartbeatDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIDCHeartbeatDo
	WriteDB() IIDCHeartbeatDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIDCHeartbeatDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIDCHeartbeatDo
	Not(conds ...gen.Condition) IIDCHeartbeatDo
	Or(conds ...gen.Condition) IIDCHeartbeatDo
	Select(conds ...field.Expr) IIDCHeartbeatDo
	Where(conds ...gen.Condition) IIDCHeartbeatDo
	Order(conds ...field.Expr) IIDCHeartbeatDo
	Distinct(cols ...field.Expr) IIDCHeartbeatDo
	Omit(cols ...field.Expr) IIDCHeartbeatDo
	Join(table schema.Tabler, on ...field.Expr) IIDCHeartbeatDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIDCHeartbeatDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIDCHeartbeatDo
	Group(cols ...field.Expr) IIDCHeartbeatDo
	Having(conds ...gen.Condition) IIDCHeartbeatDo
	Limit(limit int) IIDCHeartbeatDo
	Offset(offset int) IIDCHeartbeatDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIDCHeartbeatDo
	Unscoped() IIDCHeartbeatDo
	Create(values ...*model.IDCHeartbeat) error
	CreateInBatches(values []*model.IDCHeartbeat, batchSize int) error
	Save(values ...*model.IDCHeartbeat) error
	First() (*model.IDCHeartbeat, error)
	Take() (*model.IDCHeartbeat, error)
	Last() (*model.IDCHeartbeat, error)
	Find() ([]*model.IDCHeartbeat, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IDCHeartbeat, err error)
	FindInBatches(result *[]*model.IDCHeartbeat, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IDCHeartbeat) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIDCHeartbeatDo
	Assign(attrs ...field.AssignExpr) IIDCHeartbeatDo
	Joins(fields ...field.RelationField) IIDCHeartbeatDo
	Preload(fields ...field.RelationField) IIDCHeartbeatDo
	FirstOrInit() (*model.IDCHeartbeat, error)
	FirstOrCreate() (*model.IDCHeartbeat, error)
	FindByPage(offset int, limit int) (result []*model.IDCHeartbeat, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIDCHeartbeatDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i iDCHeartbeatDo) Debug() IIDCHeartbeatDo {
	return i.withDO(i.DO.Debug())
}

func (i iDCHeartbeatDo) WithContext(ctx context.Context) IIDCHeartbeatDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i iDCHeartbeatDo) ReadDB() IIDCHeartbeatDo {
	return i.Clauses(dbresolver.Read)
}

func (i iDCHeartbeatDo) WriteDB() IIDCHeartbeatDo {
	return i.Clauses(dbresolver.Write)
}

func (i iDCHeartbeatDo) Session(config *gorm.Session) IIDCHeartbeatDo {
	return i.withDO(i.DO.Session(config))
}

func (i iDCHeartbeatDo) Clauses(conds ...clause.Expression) IIDCHeartbeatDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i iDCHeartbeatDo) Returning(value interface{}, columns ...string) IIDCHeartbeatDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i iDCHeartbeatDo) Not(conds ...gen.Condition) IIDCHeartbeatDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i iDCHeartbeatDo) Or(conds ...gen.Condition) IIDCHeartbeatDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i iDCHeartbeatDo) Select(conds ...field.Expr) IIDCHeartbeatDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i iDCHeartbeatDo) Where(conds ...gen.Condition) IIDCHeartbeatDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i iDCHeartbeatDo) Order(conds ...field.Expr) IIDCHeartbeatDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i iDCHeartbeatDo) Distinct(cols ...field.Expr) IIDCHeartbeatDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i iDCHeartbeatDo) Omit(cols ...field.Expr) IIDCHeartbeatDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i iDCHeartbeatDo) Join(table schema.Tabler, on ...field.Expr) IIDCHeartbeatDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i iDCHeartbeatDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIDCHeartbeatDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i iDCHeartbeatDo) RightJoin(table schema.Tabler, on ...field.Expr) IIDCHeartbeatDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i iDCHeartbeatDo) Group(cols ...field.Expr) IIDCHeartbeatDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i iDCHeartbeatDo) Having(conds ...gen.Condition) IIDCHeartbeatDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i iDCHeartbeatDo) Limit(limit int) IIDCHeartbeatDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i iDCHeartbeatDo) Offset(offset int) IIDCHeartbeatDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i iDCHeartbeatDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIDCHeartbeatDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i iDCHeartbeatDo) Unscoped() IIDCHeartbeatDo {
	return i.withDO(i.DO.Unscoped())
}

func (i iDCHeartbeatDo) Create(values ...*model.IDCHeartbeat) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i iDCHeartbeatDo) CreateInBatches(values []*model.IDCHeartbeat, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i iDCHeartbeatDo) Save(values ...*model.IDCHeartbeat) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i iDCHeartbeatDo) First() (*model.IDCHeartbeat, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IDCHeartbeat), nil
	}
}

func (i iDCHeartbeatDo) Take() (*model.IDCHeartbeat, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IDCHeartbeat), nil
	}
}

func (i iDCHeartbeatDo) Last() (*model.IDCHeartbeat, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IDCHeartbeat), nil
	}
}

func (i iDCHeartbeatDo) Find() ([]*model.IDCHeartbeat, error) {
	result, err := i.DO.Find()
	return result.([]*model.IDCHeartbeat), err
}

func (i iDCHeartbeatDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IDCHeartbeat, err error) {
	buf := make([]*model.IDCHeartbeat, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i iDCHeartbeatDo) FindInBatches(result *[]*model.IDCHeartbeat, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i iDCHeartbeatDo) Attrs(attrs ...field.AssignExpr) IIDCHeartbeatDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i iDCHeartbeatDo) Assign(attrs ...field.AssignExpr) IIDCHeartbeatDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i iDCHeartbeatDo) Joins(fields ...field.RelationField) IIDCHeartbeatDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i iDCHeartbeatDo) Preload(fields ...field.RelationField) IIDCHeartbeatDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i iDCHeartbeatDo) FirstOrInit() (*model.IDCHeartbeat, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IDCHeartbeat), nil
	}
}

func (i iDCHeartbeatDo) FirstOrCreate() (*model.IDCHeartbeat, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IDCHeartbeat), nil
	}
}

func (i iDCHeartbeatDo) FindByPage(offset int, limit int) (result []*model.IDCHeartbeat, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i iDCHeartbeatDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i iDCHeartbeatDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i iDCHeartbeatDo) Delete(models ...*model.IDCHeartbeat) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *iDCHeartbeatDo) withDO(do gen.Dao) *iDCHeartbeatDo {
	i.DO = *do.(*gen.DO)
	return i
}
