// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/alert666/api-server/model"
)

func newKubernetesEvent(db *gorm.DB, opts ...gen.DOOption) kubernetesEvent {
	_kubernetesEvent := kubernetesEvent{}

	_kubernetesEvent.kubernetesEventDo.UseDB(db, opts...)
	_kubernetesEvent.kubernetesEventDo.UseModel(&model.KubernetesEvent{})

	tableName := _kubernetesEvent.kubernetesEventDo.TableName()
	_kubernetesEvent.ALL = field.NewAsterisk(tableName)
	_kubernetesEvent.ID = field.NewInt64(tableName, "id")
	_kubernetesEvent.Cluster = field.NewString(tableName, "cluster")
	_kubernetesEvent.Namespace = field.NewString(tableName, "namespace")
	_kubernetesEvent.MetadataName = field.NewString(tableName, "metadata_name")
	_kubernetesEvent.Reason = field.NewString(tableName, "reason")
	_kubernetesEvent.Name = field.NewString(tableName, "name")
	_kubernetesEvent.Kind = field.NewString(tableName, "kind")
	_kubernetesEvent.LastSeen = field.NewTime(tableName, "last_seen")
	_kubernetesEvent.FirstSeen = field.NewTime(tableName, "first_seen")
	_kubernetesEvent.Type = field.NewString(tableName, "type")
	_kubernetesEvent.Message = field.NewString(tableName, "message")
	_kubernetesEvent.Count_ = field.NewInt32(tableName, "count")
	_kubernetesEvent.ReportingComponent = field.NewString(tableName, "reporting_component")
	_kubernetesEvent.ReportingInstance = field.NewString(tableName, "reporting_instance")
	_kubernetesEvent.ApiVersion = field.NewString(tableName, "api_version")

	_kubernetesEvent.fillFieldMap()

	return _kubernetesEvent
}

type kubernetesEvent struct {
	kubernetesEventDo

	ALL                field.Asterisk
	ID                 field.Int64  // 自增主键
	Cluster            field.String // 所属集群名称
	Namespace          field.String // 资源所属命名空间
	MetadataName       field.String // 事件自身的元数据名称(唯一标识)
	Reason             field.String // 事件原因
	Name               field.String // 关联资源名称
	Kind               field.String // 关联资源类型
	LastSeen           field.Time   // 最近一次发生时间
	FirstSeen          field.Time   // 第一次发生时间
	Type               field.String // 事件类型(Normal/Warning)
	Message            field.String // 事件详细消息描述
	Count_             field.Int32  // 事件重复发生次数
	ReportingComponent field.String // 报告此事件的组件
	ReportingInstance  field.String // 报告此事件的实例(通常是Node名)
	ApiVersion         field.String // API版本

	fieldMap map[string]field.Expr
}

func (k kubernetesEvent) Table(newTableName string) *kubernetesEvent {
	k.kubernetesEventDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kubernetesEvent) As(alias string) *kubernetesEvent {
	k.kubernetesEventDo.DO = *(k.kubernetesEventDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kubernetesEvent) updateTableName(table string) *kubernetesEvent {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewInt64(table, "id")
	k.Cluster = field.NewString(table, "cluster")
	k.Namespace = field.NewString(table, "namespace")
	k.MetadataName = field.NewString(table, "metadata_name")
	k.Reason = field.NewString(table, "reason")
	k.Name = field.NewString(table, "name")
	k.Kind = field.NewString(table, "kind")
	k.LastSeen = field.NewTime(table, "last_seen")
	k.FirstSeen = field.NewTime(table, "first_seen")
	k.Type = field.NewString(table, "type")
	k.Message = field.NewString(table, "message")
	k.Count_ = field.NewInt32(table, "count")
	k.ReportingComponent = field.NewString(table, "reporting_component")
	k.ReportingInstance = field.NewString(table, "reporting_instance")
	k.ApiVersion = field.NewString(table, "api_version")

	k.fillFieldMap()

	return k
}

func (k *kubernetesEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kubernetesEvent) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 15)
	k.fieldMap["id"] = k.ID
	k.fieldMap["cluster"] = k.Cluster
	k.fieldMap["namespace"] = k.Namespace
	k.fieldMap["metadata_name"] = k.MetadataName
	k.fieldMap["reason"] = k.Reason
	k.fieldMap["name"] = k.Name
	k.fieldMap["kind"] = k.Kind
	k.fieldMap["last_seen"] = k.LastSeen
	k.fieldMap["first_seen"] = k.FirstSeen
	k.fieldMap["type"] = k.Type
	k.fieldMap["message"] = k.Message
	k.fieldMap["count"] = k.Count_
	k.fieldMap["reporting_component"] = k.ReportingComponent
	k.fieldMap["reporting_instance"] = k.ReportingInstance
	k.fieldMap["api_version"] = k.ApiVersion
}

func (k kubernetesEvent) clone(db *gorm.DB) kubernetesEvent {
	k.kubernetesEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kubernetesEvent) replaceDB(db *gorm.DB) kubernetesEvent {
	k.kubernetesEventDo.ReplaceDB(db)
	return k
}

type kubernetesEventDo struct{ gen.DO }

type IKubernetesEventDo interface {
	gen.SubQuery
	Debug() IKubernetesEventDo
	WithContext(ctx context.Context) IKubernetesEventDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKubernetesEventDo
	WriteDB() IKubernetesEventDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKubernetesEventDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKubernetesEventDo
	Not(conds ...gen.Condition) IKubernetesEventDo
	Or(conds ...gen.Condition) IKubernetesEventDo
	Select(conds ...field.Expr) IKubernetesEventDo
	Where(conds ...gen.Condition) IKubernetesEventDo
	Order(conds ...field.Expr) IKubernetesEventDo
	Distinct(cols ...field.Expr) IKubernetesEventDo
	Omit(cols ...field.Expr) IKubernetesEventDo
	Join(table schema.Tabler, on ...field.Expr) IKubernetesEventDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKubernetesEventDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKubernetesEventDo
	Group(cols ...field.Expr) IKubernetesEventDo
	Having(conds ...gen.Condition) IKubernetesEventDo
	Limit(limit int) IKubernetesEventDo
	Offset(offset int) IKubernetesEventDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKubernetesEventDo
	Unscoped() IKubernetesEventDo
	Create(values ...*model.KubernetesEvent) error
	CreateInBatches(values []*model.KubernetesEvent, batchSize int) error
	Save(values ...*model.KubernetesEvent) error
	First() (*model.KubernetesEvent, error)
	Take() (*model.KubernetesEvent, error)
	Last() (*model.KubernetesEvent, error)
	Find() ([]*model.KubernetesEvent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KubernetesEvent, err error)
	FindInBatches(result *[]*model.KubernetesEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.KubernetesEvent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKubernetesEventDo
	Assign(attrs ...field.AssignExpr) IKubernetesEventDo
	Joins(fields ...field.RelationField) IKubernetesEventDo
	Preload(fields ...field.RelationField) IKubernetesEventDo
	FirstOrInit() (*model.KubernetesEvent, error)
	FirstOrCreate() (*model.KubernetesEvent, error)
	FindByPage(offset int, limit int) (result []*model.KubernetesEvent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKubernetesEventDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k kubernetesEventDo) Debug() IKubernetesEventDo {
	return k.withDO(k.DO.Debug())
}

func (k kubernetesEventDo) WithContext(ctx context.Context) IKubernetesEventDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kubernetesEventDo) ReadDB() IKubernetesEventDo {
	return k.Clauses(dbresolver.Read)
}

func (k kubernetesEventDo) WriteDB() IKubernetesEventDo {
	return k.Clauses(dbresolver.Write)
}

func (k kubernetesEventDo) Session(config *gorm.Session) IKubernetesEventDo {
	return k.withDO(k.DO.Session(config))
}

func (k kubernetesEventDo) Clauses(conds ...clause.Expression) IKubernetesEventDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kubernetesEventDo) Returning(value interface{}, columns ...string) IKubernetesEventDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kubernetesEventDo) Not(conds ...gen.Condition) IKubernetesEventDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kubernetesEventDo) Or(conds ...gen.Condition) IKubernetesEventDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kubernetesEventDo) Select(conds ...field.Expr) IKubernetesEventDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kubernetesEventDo) Where(conds ...gen.Condition) IKubernetesEventDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kubernetesEventDo) Order(conds ...field.Expr) IKubernetesEventDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kubernetesEventDo) Distinct(cols ...field.Expr) IKubernetesEventDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kubernetesEventDo) Omit(cols ...field.Expr) IKubernetesEventDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kubernetesEventDo) Join(table schema.Tabler, on ...field.Expr) IKubernetesEventDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kubernetesEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKubernetesEventDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kubernetesEventDo) RightJoin(table schema.Tabler, on ...field.Expr) IKubernetesEventDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kubernetesEventDo) Group(cols ...field.Expr) IKubernetesEventDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kubernetesEventDo) Having(conds ...gen.Condition) IKubernetesEventDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kubernetesEventDo) Limit(limit int) IKubernetesEventDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kubernetesEventDo) Offset(offset int) IKubernetesEventDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kubernetesEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKubernetesEventDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kubernetesEventDo) Unscoped() IKubernetesEventDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kubernetesEventDo) Create(values ...*model.KubernetesEvent) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kubernetesEventDo) CreateInBatches(values []*model.KubernetesEvent, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kubernetesEventDo) Save(values ...*model.KubernetesEvent) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kubernetesEventDo) First() (*model.KubernetesEvent, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KubernetesEvent), nil
	}
}

func (k kubernetesEventDo) Take() (*model.KubernetesEvent, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KubernetesEvent), nil
	}
}

func (k kubernetesEventDo) Last() (*model.KubernetesEvent, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KubernetesEvent), nil
	}
}

func (k kubernetesEventDo) Find() ([]*model.KubernetesEvent, error) {
	result, err := k.DO.Find()
	return result.([]*model.KubernetesEvent), err
}

func (k kubernetesEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KubernetesEvent, err error) {
	buf := make([]*model.KubernetesEvent, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kubernetesEventDo) FindInBatches(result *[]*model.KubernetesEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kubernetesEventDo) Attrs(attrs ...field.AssignExpr) IKubernetesEventDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kubernetesEventDo) Assign(attrs ...field.AssignExpr) IKubernetesEventDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kubernetesEventDo) Joins(fields ...field.RelationField) IKubernetesEventDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kubernetesEventDo) Preload(fields ...field.RelationField) IKubernetesEventDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kubernetesEventDo) FirstOrInit() (*model.KubernetesEvent, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KubernetesEvent), nil
	}
}

func (k kubernetesEventDo) FirstOrCreate() (*model.KubernetesEvent, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KubernetesEvent), nil
	}
}

func (k kubernetesEventDo) FindByPage(offset int, limit int) (result []*model.KubernetesEvent, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kubernetesEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kubernetesEventDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kubernetesEventDo) Delete(models ...*model.KubernetesEvent) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kubernetesEventDo) withDO(do gen.Dao) *kubernetesEventDo {
	k.DO = *do.(*gen.DO)
	return k
}
