// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/alert666/api-server/base/app"
	"github.com/alert666/api-server/base/conf"
	"github.com/alert666/api-server/base/data"
	"github.com/alert666/api-server/base/middleware"
	"github.com/alert666/api-server/base/router"
	"github.com/alert666/api-server/base/server"
	"github.com/alert666/api-server/controller"
	"github.com/alert666/api-server/grpc/handler"
	server2 "github.com/alert666/api-server/grpc/server"
	"github.com/alert666/api-server/pkg/alertinhibit"
	"github.com/alert666/api-server/pkg/casbin"
	"github.com/alert666/api-server/pkg/feishu"
	"github.com/alert666/api-server/pkg/jwt"
	"github.com/alert666/api-server/pkg/local_cache"
	"github.com/alert666/api-server/pkg/oauth"
	"github.com/alert666/api-server/service/v1"
	"github.com/alert666/api-server/store"
)

// Injectors from wire.go:

func InitApplication() (*app.Application, func(), error) {
	client, err := data.NewRDB()
	if err != nil {
		return nil, nil, err
	}
	cacheStore, cleanup, err := store.NewCacheStore(client)
	if err != nil {
		return nil, nil, err
	}
	generateToken, err := jwt.NewGenerateToken()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	oAuth2, err := oauth.NewOAuth2()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cacher := localcache.NewCacher(oAuth2)
	userServicer := v1.NewUserService(cacheStore, generateToken, oAuth2, cacher)
	userController := controller.NewUserController(userServicer)
	db, cleanup2, err := data.NewDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	enforcer, err := casbin.NewEnforcer(db)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinManager := casbin.NewCasbinManager(enforcer)
	roleServicer := v1.NewRoleService(casbinManager)
	roleController := controller.NewRoleController(roleServicer)
	apiServicer := v1.NewApiServicer()
	apiController := controller.NewApiController(apiServicer)
	tenantServicer := v1.NewTenantServicer(cacheStore)
	clusterController := controller.NewClusterController(tenantServicer)
	feishuer := feishu.NewFeiShu()
	alertsServicer := v1.NewAlertsServicer(cacheStore, feishuer)
	alertManagerController := controller.NewAlertManagerController(alertsServicer)
	authChecker := casbin.NewAuthChecker(enforcer)
	middlewareMiddleware := middleware.NewMiddleware(generateToken, authChecker, cacheStore)
	alertTemplateServicer := v1.NewAlertTemplateServicer(cacheStore)
	alertTemplateController := controller.NewAlertTemplateController(alertTemplateServicer)
	alertChannelServicer := v1.NewChannelServicer(cacheStore)
	alertChannelController := controller.NewAlertChannelController(alertChannelServicer)
	alertHistoryServicer := v1.NewHistoryServicer(cacheStore)
	alertHistoryController := controller.NewAlertHistoryController(alertHistoryServicer)
	alertSilenceServicer := v1.NewAlertSilenceServicer(generateToken)
	alertSilenceController := controller.NewAlertSilenceController(alertSilenceServicer)
	dataTunnelServicer := v1.NewDataTunnelService(cacheStore)
	agentCommandController := controller.NewAgentCommandController(dataTunnelServicer)
	internalForwardController := controller.NewInternalForwardController(dataTunnelServicer)
	routerRouter := router.NewRouter(userController, roleController, apiController, clusterController, alertManagerController, middlewareMiddleware, alertTemplateController, alertChannelController, alertHistoryController, alertSilenceController, agentCommandController, internalForwardController)
	engine, err := server.NewHttpServer(routerRouter)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	cleanDuplicateFiringer := v1.NewCleanDuplicateFiringer(cacheStore)
	cleanExpiredSilencer := v1.NewCleanExpiredSilencer(cacheStore)
	v, err := alertinhibit.NewMatchers()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	alertInhibiter := v1.NewalertInhibit(v, cacheStore)
	cacheAlertNameOptioner := v1.NewCacheAlertNameOptioner(cacheStore)
	string2 := NewGRPCBindAddress()
	tunnelHandler := handler.NewTunnelHandler(dataTunnelServicer)
	grpcServer, err := server2.NewGRPCServer(string2, tunnelHandler)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	application := app.NewApplication(engine, cacheStore, feishuer, cleanDuplicateFiringer, cleanExpiredSilencer, alertInhibiter, cacheAlertNameOptioner, grpcServer)
	return application, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// NewGRPCBindAddress 锟结供 gRPC 锟斤拷锟斤拷锟斤拷址
func NewGRPCBindAddress() string {
	return conf.GetGRPCBind()
}
